manifest = "0a54cd0d6ab6799b60f6af0a768b23dcff7a3d6e285116a744ede4053bf5e606"

[[dependency]]
package = "github.com/buckaroo-pm/mapbox-geometry.hpp"
target = "//:geometry"

[[dependency]]
package = "github.com/buckaroo-pm/mapbox-rapidjson"
target = "//:rapidjson"

[[lock]]
name = "github.com/buckaroo-pm/Catch2"
revision = "65ab25beb9080c77a7aa0edbfab1812a06e174d1"

[[lock]]
name = "github.com/buckaroo-pm/mapbox-geometry.hpp"
revision = "dc886c9705ebec3b4c8ddf3b305537a450267944"

[[lock]]
name = "github.com/buckaroo-pm/mapbox-rapidjson"
revision = "44ccecfb229c4862ef4fa924a4841749196abfc7"

[[lock]]
name = "github.com/buckaroo-pm/mapbox-variant"
revision = "e735b7c1be9fe58e364685e6093628644776baf3"
